-- MySQL Script generated by MySQL Workbench
-- Wed May 25 17:05:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


DROP TABLE IF EXISTS `tipo_documento` ;

CREATE TABLE IF NOT EXISTS `tipo_documento` (
  `codigo` CHAR(3) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

CREATE TABLE IF NOT EXISTS `usuario` (
  `num_documento` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `nombre(s)` VARCHAR(45) NULL,
  `apellido(s)` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `email` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `tipo_documento_codigo` CHAR(3) NOT NULL,
  PRIMARY KEY (`num_documento`),
  INDEX `fk_usuario_tipo_documento1_idx` (`tipo_documento_codigo` ASC) ,
  CONSTRAINT `fk_usuario_tipo_documento1`
    FOREIGN KEY (`tipo_documento_codigo`)
    REFERENCES `tipo_documento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `documento` ;

CREATE TABLE IF NOT EXISTS `documento` (
  `codigo` INT NOT NULL,
  `nombre(s)` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `fecha_creación` VARCHAR(45) NULL,
  `usuario_num_documento` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_Documento_Usuario1_idx` (`usuario_num_documento` ASC) ,
  CONSTRAINT `fk_Documento_Usuario1`
    FOREIGN KEY (`usuario_num_documento`)
    REFERENCES `usuario` (`num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `area` ;

CREATE TABLE IF NOT EXISTS `area` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `acudiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `acudiente` ;

CREATE TABLE IF NOT EXISTS `acudiente` (
  `num_documento` INT NOT NULL,
  `nombre(s)` VARCHAR(45) NULL,
  `apelido(s)` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `dirección` VARCHAR(45) NULL,
  `parentesco` VARCHAR(45) NULL,
  `tipo_documento_codigo` CHAR(3) NOT NULL,
  PRIMARY KEY (`num_documento`),
  INDEX `fk_acudiente_tipo_documento1_idx` (`tipo_documento_codigo` ASC) ,
  CONSTRAINT `fk_acudiente_tipo_documento1`
    FOREIGN KEY (`tipo_documento_codigo`)
    REFERENCES `tipo_documento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `docente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `docente` ;

CREATE TABLE IF NOT EXISTS `docente` (
  `profesión` VARCHAR(45) NULL,
  `usuario_num_documento` INT NOT NULL,
  INDEX `fk_Docente_Usuario_idx` (`usuario_num_documento` ASC) ,
  PRIMARY KEY (`usuario_num_documento`),
  CONSTRAINT `fk_Docente_Usuario`
    FOREIGN KEY (`usuario_num_documento`)
    REFERENCES `usuario` (`num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `administrativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `administrativo` ;

CREATE TABLE IF NOT EXISTS `administrativo` (
  `eps` VARCHAR(45) NULL,
  `fondo_pensional` VARCHAR(45) NULL,
  `usuario_num_documento` INT NOT NULL,
  INDEX `fk_Administrativo_Usuario1_idx` (`usuario_num_documento` ASC) ,
  CONSTRAINT `fk_Administrativo_Usuario1`
    FOREIGN KEY (`usuario_num_documento`)
    REFERENCES `usuario` (`num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materia` ;

CREATE TABLE IF NOT EXISTS `materia` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `hrs_semana` INT NULL,
  `area_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_Materia_Area1_idx` (`area_codigo` ASC) ,
  CONSTRAINT `fk_Materia_Area1`
    FOREIGN KEY (`area_codigo`)
    REFERENCES `area` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudiante` ;

CREATE TABLE IF NOT EXISTS `estudiante` (
  `num_documento` INT NOT NULL,
  `nombre(s)` VARCHAR(45) NULL,
  `apellido(s)` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `dirección` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `estado` INT(1) NULL,
  `acudiente_num_documento` INT NOT NULL,
  `tipo_documento_codigo` CHAR(3) NOT NULL,
  PRIMARY KEY (`num_documento`),
  INDEX `fk_Estudiante_Acudiente1_idx` (`acudiente_num_documento` ASC) ,
  INDEX `fk_Estudiante_tipo_documento1_idx` (`tipo_documento_codigo` ASC) ,
  CONSTRAINT `fk_Estudiante_Acudiente1`
    FOREIGN KEY (`acudiente_num_documento`)
    REFERENCES `acudiente` (`num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_tipo_documento1`
    FOREIGN KEY (`tipo_documento_codigo`)
    REFERENCES `tipo_documento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `grupo` ;

CREATE TABLE IF NOT EXISTS `grupo` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `anio` INT(4) NULL,
  `estudiante_num_documento` INT NOT NULL,
  `docente_num_documento` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_Grupo_Estudiante1_idx` (`estudiante_num_documento` ASC) ,
  INDEX `fk_Grupo_Docente1_idx` (`docente_num_documento` ASC) ,
  CONSTRAINT `fk_Grupo_Estudiante1`
    FOREIGN KEY (`estudiante_num_documento`)
    REFERENCES `estudiante` (`num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_Docente1`
    FOREIGN KEY (`docente_num_documento`)
    REFERENCES `docente` (`usuario_num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `periodo` ;

CREATE TABLE IF NOT EXISTS `periodo` (
  `codigo` INT NOT NULL,
  `nombre(s)` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `materia_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `materia_grupo` ;

CREATE TABLE IF NOT EXISTS `materia_grupo` (
  `materia_codigo` INT NOT NULL,
  `grupo_codigo` INT NOT NULL,
  PRIMARY KEY (`materia_codigo`, `grupo_codigo`),
  INDEX `fk_Materia_has_Grupo_Grupo1_idx` (`grupo_codigo` ASC) ,
  INDEX `fk_Materia_has_Grupo_Materia1_idx` (`materia_codigo` ASC) ,
  CONSTRAINT `fk_Materia_has_Grupo_Materia1`
    FOREIGN KEY (`materia_codigo`)
    REFERENCES `materia` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materia_has_Grupo_Grupo1`
    FOREIGN KEY (`grupo_codigo`)
    REFERENCES `grupo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nota` ;

CREATE TABLE IF NOT EXISTS `nota` (
  `estudiante_num_documento` INT NOT NULL,
  `periodo_codigo` INT NOT NULL,
  `materia_codigo` INT NOT NULL,
  `grupo_codigo` INT NOT NULL,
  `nota` FLOAT(10,2) NULL,
  PRIMARY KEY (`estudiante_num_documento`, `periodo_codigo`),
  INDEX `fk_Estudiante_has_Periodo_Periodo1_idx` (`periodo_codigo` ASC) ,
  INDEX `fk_Estudiante_has_Periodo_Estudiante1_idx` (`estudiante_num_documento` ASC) ,
  INDEX `fk_Estudiante_has_Periodo_Materia_has_Grupo1_idx` (`materia_codigo` ASC, `grupo_codigo` ASC) ,
  CONSTRAINT `fk_Estudiante_has_Periodo_Estudiante1`
    FOREIGN KEY (`estudiante_num_documento`)
    REFERENCES `estudiante` (`num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Periodo_Periodo1`
    FOREIGN KEY (`periodo_codigo`)
    REFERENCES `periodo` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Periodo_Materia_has_Grupo1`
    FOREIGN KEY (`materia_codigo` , `grupo_codigo`)
    REFERENCES `materia_grupo` (`materia_codigo` , `grupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horario` ;

CREATE TABLE IF NOT EXISTS `horario` (
  `dia` VARCHAR(20) NOT NULL,
  `hora_inicio` DATETIME NULL,
  `hora_fin` DATETIME NULL,
  `materia_codigo` INT NOT NULL,
  `grupo_codigo` INT NOT NULL,
  INDEX `fk_horario_Materia_has_Grupo1_idx` (`materia_codigo` ASC, `grupo_codigo` ASC) ,
  CONSTRAINT `fk_horario_Materia_has_Grupo1`
    FOREIGN KEY (`materia_codigo` , `grupo_codigo`)
    REFERENCES `materia_grupo` (`materia_codigo` , `grupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `indicador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `indicador` ;

CREATE TABLE IF NOT EXISTS `indicador` (
  `codigo` INT NOT NULL,
  `sigla` VARCHAR(10) NULL,
  `descripcion` VARCHAR(300) NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nota_indicador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nota_indicador` ;

CREATE TABLE IF NOT EXISTS `nota_indicador` (
  `indicador_codigo` INT NOT NULL,
  `nota_estudiante_num_documento` INT NOT NULL,
  `nota_periodo_codigo` INT NOT NULL,
  PRIMARY KEY (`indicador_codigo`, `nota_estudiante_num_documento`, `nota_periodo_codigo`),
  INDEX `fk_indicador_has_Estudiante_has_Periodo_indicador1_idx` (`indicador_codigo` ASC) ,
  INDEX `fk_nota_indicador_nota1_idx` (`nota_estudiante_num_documento` ASC, `nota_periodo_codigo` ASC) ,
  CONSTRAINT `fk_indicador_has_Estudiante_has_Periodo_indicador1`
    FOREIGN KEY (`indicador_codigo`)
    REFERENCES `indicador` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_indicador_nota1`
    FOREIGN KEY (`nota_estudiante_num_documento` , `nota_periodo_codigo`)
    REFERENCES `nota` (`estudiante_num_documento` , `periodo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `licencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `licencia` ;

CREATE TABLE IF NOT EXISTS `licencia` (
  `id_licencia` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `descripcion` VARCHAR(400) NOT NULL,
  `usuario_num_documento` INT NOT NULL,
  PRIMARY KEY (`id_licencia`),
  INDEX `fk_licencia_usuario1_idx` (`usuario_num_documento` ASC) ,
  CONSTRAINT `fk_licencia_usuario1`
    FOREIGN KEY (`usuario_num_documento`)
    REFERENCES `usuario` (`num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sancion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sancion` ;

CREATE TABLE IF NOT EXISTS `sancion` (
  `idsancion` INT NOT NULL,
  `fecha` DATE NULL,
  `motivo` VARCHAR(80) NULL,
  `descripcion` VARCHAR(500) NULL,
  `estudiante_num_documento` INT NOT NULL,
  PRIMARY KEY (`idsancion`),
  INDEX `fk_sancion_estudiante1_idx` (`estudiante_num_documento` ASC) ,
  CONSTRAINT `fk_sancion_estudiante1`
    FOREIGN KEY (`estudiante_num_documento`)
    REFERENCES `estudiante` (`num_documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
